/*
 * VersionInfo.java
 *
 * Created on 01 January 2002, 21:26
 */

package uk.ac.leeds.ccg.geotools;

/**
 *
 * @author  James Macgill
 */
public class VersionInfo extends java.awt.Dialog {
    public static final String date = "$Date";
    /** Creates new form VersionInfo */
    public VersionInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setLayout(new java.awt.GridBagLayout());

        setResizable(false);
        setTitle("Version info for GeoTools Open Source GIS tooklit");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 14));
        label1.setName("version");
        label1.setText("Version : 0.8.0");
        label1.setAlignment(java.awt.Label.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 327;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(100, 0, 0, 0);
        add(label1, gridBagConstraints);

        label2.setText("GeoTools is (c) 2002 James Macgill and is made available under the LGPL licence");
        label2.setAlignment(java.awt.Label.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 29;
        add(label2, gridBagConstraints);

        label3.setText("See http://www.geotools.org for details on using this library");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 0, 0);
        add(label3, gridBagConstraints);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(476, 302));
        setLocation((screenSize.width-476)/2,(screenSize.height-302)/2);
    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        if(args.length>0){
            System.out.println(args[0]);
        }
        new VersionInfo(new java.awt.Frame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label3;
    private java.awt.Label label2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
